### ISSUE TITLE
how to change the swipe direction

### ISSUE THREAD

**Issue by iljyya** [Yellow5A5/Material-Design-Login#1]
can I swipe left to go to the right side, like the usual viewpager?

**Comment by Yellow5A5** [comment]
Yes, of course.
```
//you can doing something you wanted.
public interface IScrollCallBack {
    void onScrollProcess(int process, boolean isLeft);
}
public void setIScrollCallBack(IScrollCallBack l) {
    mIScrollCallBack = l;
}
```
It's different from Viewpager. This library just provides the capability for sliding callback. Viewpager is generally used as a container. it's different scenes. If you can use Viewpager to implement, you don't need to use this library. @iljyya
